AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pp-scores-api

  Sample SAM Template for pp-scores-api
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 6

Resources:
  GraphQLFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: graphql.handler
      Runtime: nodejs14.x
      CodeUri: graphql/
      Architectures:
        - x86_64
      Events:
        AnyRequest:
          Type: Api
          Properties:
            Path: /graphql
            Method: ANY

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GraphQLFunction:
    Description: "GraphQL Lambda Function ARN"
    Value: !GetAtt GraphQLFunction.Arn
  GraphQLFunctionIamRole:
    Description: "Implicit IAM Role created for GraphQL function"
    Value: !GetAtt GraphQLFunction.Arn
  GraphQLApi:
    Description: "API Gateway endpoint URL for Prod stage for GraphQL function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/graphql/"
